Project 1 by Joe Chan
=====================

## Python Code:
```python
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
df = pd.read_csv('Downloads/is362_project1.csv', header=None)

print (df)

df.columns = ['airline','city','on_time','delayed']

alaska = df[:5]
print (alaska)
amwest = df[5:10]
print (amwest)

alaska_avg_ontime = alaska['on_time'].mean()
alaska_avg_delayed = alaska['delayed'].mean()

amwest_avg_ontime = amwest['on_time'].mean()
amwest_avg_delayed = amwest['delayed'].mean()

alaska_describe_ontime = alaska['on_time'].describe()
print ("Describe On Time stats for Alaska Airlines: ")
print (alaska_describe_ontime)
amwest_describe_ontime = amwest['on_time'].describe()
print ("Describe On Time stats for AM West Airlines: ")
print (amwest_describe_ontime)

alaska_describe_delayed = alaska['delayed'].describe()
print ("Describe Delayed stats for Alaska Airlines: ")
print (alaska_describe_delayed)
amwest_describe_delayed = amwest['delayed'].describe()
print ("Describe Delayed stats for AM West Airlines: ")
print (amwest_describe_delayed)

alaska_sum_ontime = alaska['on_time'].sum()
alaska_sum_delayed = alaska['delayed'].sum()

amwest_sum_ontime = amwest['on_time'].sum()
amwest_sum_delayed = amwest['delayed'].sum()

print ("The average number of On Time Arrivals for Alaska Airlines is: ", alaska_avg_ontime)
print ("The average number of Delayed Arrivals for Alaska Airlines is: ", alaska_avg_delayed)

print ("The average number of On Time Arrivals for AM West Airlines is: ", amwest_avg_ontime)
print ("The average number of Delayed Arrivals for AM West Airlines is: ", amwest_avg_delayed)

print ("The total number of On Time Arrivals for Alaska Airlines is: ", alaska_sum_ontime)
print ("The total number of Delayed Arrivals for Alaska Airlines is: ", alaska_sum_delayed)

print ("The total number of On Time Arrivals for AM West Airlines is: ", amwest_sum_ontime)
print ("The total number of Delayed Arrivals for AM West Airlines is: ", amwest_sum_delayed)
   

```

This python code reads the CSV file into a panda Data Frame variable called "df"

The Data Frame is into 2 different Data Frames called "alaska" for Alaska Airlines and "amwest" for AM West Airlines.

The code describes the On Time and Delayed statistics for Alaska and AM West.
The code then compares the average number delayed and on time arrivals for Alaska and AM West Airlines.
Lastly, the code comopares the sum of On Time and Delayed arrivals for Alaska and AM West Airlines.

Below is the Python code that can be run in the Jupyter Notebook:

In [15]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
df = pd.read_csv('Downloads/is362_project1.csv', header=None)

print (df)

df.columns = ['airline','city','on_time','delayed']

alaska = df[:5]
print (alaska)
amwest = df[5:10]
print (amwest)

alaska_avg_ontime = alaska['on_time'].mean()
alaska_avg_delayed = alaska['delayed'].mean()

amwest_avg_ontime = amwest['on_time'].mean()
amwest_avg_delayed = amwest['delayed'].mean()

alaska_describe_ontime = alaska['on_time'].describe()
print ("Describe On Time stats for Alaska Airlines: ")
print (alaska_describe_ontime)
amwest_describe_ontime = amwest['on_time'].describe()
print ("Describe On Time stats for AM West Airlines: ")
print (amwest_describe_ontime)

alaska_describe_delayed = alaska['delayed'].describe()
print ("Describe Delayed stats for Alaska Airlines: ")
print (alaska_describe_delayed)
amwest_describe_delayed = amwest['delayed'].describe()
print ("Describe Delayed stats for AM West Airlines: ")
print (amwest_describe_delayed)

alaska_sum_ontime = alaska['on_time'].sum()
alaska_sum_delayed = alaska['delayed'].sum()

amwest_sum_ontime = amwest['on_time'].sum()
amwest_sum_delayed = amwest['delayed'].sum()

print ("The average number of On Time Arrivals for Alaska Airlines is: ", alaska_avg_ontime)
print ("The average number of Delayed Arrivals for Alaska Airlines is: ", alaska_avg_delayed)

print ("The average number of On Time Arrivals for AM West Airlines is: ", amwest_avg_ontime)
print ("The average number of Delayed Arrivals for AM West Airlines is: ", amwest_avg_delayed)

print ("The total number of On Time Arrivals for Alaska Airlines is: ", alaska_sum_ontime)
print ("The total number of Delayed Arrivals for Alaska Airlines is: ", alaska_sum_delayed)

print ("The total number of On Time Arrivals for AM West Airlines is: ", amwest_sum_ontime)
print ("The total number of Delayed Arrivals for AM West Airlines is: ", amwest_sum_delayed)

        0              1     2    3
0  ALASKA    Los Angeles   497   62
1  ALASKA        Phoenix   221   12
2  ALASKA      San Diego   212   20
3  ALASKA  San Francisco   503  102
4  ALASKA        Seattle  1841  305
5  AMWEST    Los Angeles   694  117
6  AMWEST        Phoenix  4840  415
7  AMWEST      San Diego   393   65
8  AMWEST  San Francisco   320  129
9  AMWEST        Seattle   201   61
  airline           city  on_time  delayed
0  ALASKA    Los Angeles      497       62
1  ALASKA        Phoenix      221       12
2  ALASKA      San Diego      212       20
3  ALASKA  San Francisco      503      102
4  ALASKA        Seattle     1841      305
  airline           city  on_time  delayed
5  AMWEST    Los Angeles      694      117
6  AMWEST        Phoenix     4840      415
7  AMWEST      San Diego      393       65
8  AMWEST  San Francisco      320      129
9  AMWEST        Seattle      201       61
Describe On Time stats for Alaska Airlines:
count       5.000000
mean      654.800000
std       678.098223
min       212.000000
25%       221.000000
50%       497.000000
75%       503.000000
max      1841.000000
Name: on_time, dtype: float64
Describe On Time stats for AM West Airlines:
count       5.000000
mean     1289.600000
std      1993.059532
min       201.000000
25%       320.000000
50%       393.000000
75%       694.000000
max      4840.000000
Name: on_time, dtype: float64
Describe Delayed stats for Alaska Airlines:
count      5.000000
mean     100.200000
std      120.017499
min       12.000000
25%       20.000000
50%       62.000000
75%      102.000000
max      305.000000
Name: delayed, dtype: float64
Describe Delayed stats for AM West Airlines:
count      5.000000
mean     157.400000
std      147.162495
min       61.000000
25%       65.000000
50%      117.000000
75%      129.000000
max      415.000000
Name: delayed, dtype: float64
The average number of On Time Arrivals for Alaska Airlines is:  654.8
The average number of Delayed Arrivals for Alaska Airlines is:  100.2
The average number of On Time Arrivals for AM West Airlines is:  1289.6
The average number of Delayed Arrivals for AM West Airlines is:  157.4
The total number of On Time Arrivals for Alaska Airlines is:  3274
The total number of Delayed Arrivals for Alaska Airlines is:  501
The total number of On Time Arrivals for AM West Airlines is:  6448
The total number of Delayed Arrivals for AM West Airlines is:  787